package com.erp.view.panels.orders;

import com.erp.view.panels.StubTabPanel;

public class ReportingAnalyticsTab extends StubTabPanel {
    public ReportingAnalyticsTab() {
        super(
                "Reports & Analytics",
                "Operational reports across orders, revenue, and trends.",
                new String[]{"Report", "Period", "Generated By", "Format", "Status"},
                "Run Report", "Schedule", "Export", "Share"
        );
    }
}
